In [1]:
import pandas as pd
import numpy as np
import requests

In [13]:
pd.set_option('display.max_rows', 2000)

In [3]:
def getdata(url):
  r = requests.get(url,headers ={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'})
  data = pd.read_html(r.text)
  return data

In [4]:
stock = "S32"

In [6]:
summary_url = f'https://finance.yahoo.com/quote/{stock}.AX?p={stock}.AX&.tsrc=fin-srch'
summary_data = getdata(summary_url)
summary_data

[                0                1
 0  Previous Close           4.6400
 1            Open           4.7000
 2             Bid       4.6200 x 0
 3             Ask       4.6300 x 0
 4     Day's Range  4.6000 - 4.7100
 5   52 Week Range  3.4000 - 5.4400
 6          Volume         13954404
 7     Avg. Volume         18243573,
                           0             1
 0                Market Cap       21.123B
 1         Beta (5Y Monthly)          1.03
 2            PE Ratio (TTM)          5.63
 3                 EPS (TTM)        0.8200
 4             Earnings Date  Feb 16, 2023
 5  Forward Dividend & Yield  0.34 (7.38%)
 6          Ex-Dividend Date  Sep 15, 2022
 7             1y Target Est          5.05]

In [7]:
data = pd.concat(summary_data)
data.reset_index(drop=True, inplace=True)
data

                           0                1
0             Previous Close           4.6400
1                       Open           4.7000
2                        Bid       4.6200 x 0
3                        Ask       4.6300 x 0
4                Day's Range  4.6000 - 4.7100
5              52 Week Range  3.4000 - 5.4400
6                     Volume         13954404
7                Avg. Volume         18243573
8                 Market Cap          21.123B
9          Beta (5Y Monthly)             1.03
10            PE Ratio (TTM)             5.63
11                 EPS (TTM)           0.8200
12             Earnings Date     Feb 16, 2023
13  Forward Dividend & Yield     0.34 (7.38%)
14          Ex-Dividend Date     Sep 15, 2022
15             1y Target Est             5.05

In [8]:
df = data.transpose()
df.columns = df.iloc[0]
df = df.drop(0)
df = df.reset_index(drop=True)

In [9]:
df

,Previous Close,Open,Bid,Ask,Day's Range,52 Week Range,Volume,Avg. Volume,Market Cap,Beta (5Y Monthly),PE Ratio (TTM),EPS (TTM),Earnings Date,Forward Dividend & Yield,Ex-Dividend Date,1y Target Est
0,4.6400,4.7000,4.6200 x 0,4.6300 x 0,4.6000 - 4.7100,3.4000 - 5.4400,13954404,18243573,21.123B,1.03,5.63,0.8200,"Feb 16, 2023",0.34 (7.38%),"Sep 15, 2022",5.05

In [15]:
historical_url= f'https://finance.yahoo.com/quote/{stock}.AX/history?period1=1518652800&period2=1676419200&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true'

#https://finance.yahoo.com/quote/{stock}/history?p={stock}'
historical_data = getdata(historical_url)
data = historical_data[0]
data = data.iloc[:-1, :]
data = data[data["Open"].str.contains("Dividend") == False]

In [16]:
data['Date'] = pd.to_datetime(data['Date'])
numeric_columns = list(data.columns)[1::]
for column_name in numeric_columns:
    data[column_name] = data[column_name].str.replace(',', '')
    data[column_name] = data[column_name].astype(np.float64)

In [17]:
data

         Date  Open   High    Low  Close*  Adj Close**      Volume
0  2023-02-15  4.70  4.710  4.600    4.62         4.62  13954404.0
1  2023-02-14  4.67  4.680  4.630    4.64         4.64  13282276.0
2  2023-02-13  4.60  4.640  4.540    4.58         4.58  20136910.0
3  2023-02-10  4.68  4.690  4.580    4.58         4.58  13638584.0
4  2023-02-09  4.68  4.720  4.660    4.69         4.69  13261399.0
5  2023-02-08  4.68  4.750  4.680    4.74         4.74  17160560.0
6  2023-02-07  4.63  4.700  4.620    4.64         4.64  14449945.0
7  2023-02-06  4.63  4.680  4.580    4.61         4.61   7988953.0
8  2023-02-03  4.60  4.755  4.600    4.68         4.68  18966172.0
9  2023-02-02  4.73  4.815  4.700    4.72         4.72  20550756.0
10 2023-02-01  4.61  4.650  4.595    4.63         4.63  13912353.0
11 2023-01-31  4.62  4.655  4.530    4.54         4.54  23492653.0
12 2023-01-30  4.73  4.740  4.645    4.67         4.67  13413638.0
13 2023-01-27  4.65  4.710  4.630    4.71         4.71  25854453.0
14 2023-01-25  4.83  4.840  4.740    4.76         4.76  16506843.0
15 2023-01-24  4.72  4.870  4.700    4.83         4.83  19713251.0
16 2023-01-23  4.52  4.670  4.520    4.63         4.63  19139841.0
17 2023-01-20  4.60  4.615  4.555    4.57         4.57  25270418.0
18 2023-01-19  4.53  4.580  4.505    4.56         4.56  18125535.0
19 2023-01-18  4.54  4.550  4.480    4.51         4.51  19967385.0
20 2023-01-17  4.62  4.640  4.500    4.56         4.56  19491001.0
21 2023-01-16  4.65  4.720  4.640    4.70         4.70  15591090.0
22 2023-01-13  4.57  4.640  4.560    4.60         4.60  20241643.0
23 2023-01-12  4.55  4.630  4.520    4.55         4.55  15574405.0
24 2023-01-11  4.47  4.545  4.450    4.50         4.50  16870817.0
25 2023-01-10  4.43  4.500  4.430    4.45         4.45  15716687.0
26 2023-01-09  4.38  4.450  4.365    4.41         4.41  20074007.0
27 2023-01-06  4.11  4.260  4.110    4.25         4.25  18456584.0
28 2023-01-05  4.12  4.130  4.060    4.07         4.07  13388326.0
29 2023-01-04  3.99  4.070  3.980    4.07         4.07  12362739.0
30 2023-01-03  4.02  4.030  3.910    3.94         3.94  10515163.0
31 2022-12-30  4.03  4.060  3.975    4.00         4.00  12388056.0
32 2022-12-29  4.05  4.065  3.960    3.99         3.99  14383064.0
33 2022-12-28  4.08  4.115  4.060    4.11         4.11   9109289.0
34 2022-12-23  4.08  4.110  4.060    4.07         4.07   9091070.0
35 2022-12-22  4.16  4.180  4.090    4.10         4.10  16292808.0
36 2022-12-21  4.05  4.150  4.015    4.10         4.10  14703043.0
37 2022-12-20  4.06  4.100  4.020    4.03         4.03  14738121.0
38 2022-12-19  4.12  4.180  4.120    4.13         4.13   9803846.0
39 2022-12-16  4.15  4.195  4.100    4.10         4.10  31134213.0
40 2022-12-15  4.20  4.230  4.150    4.19         4.19  15563307.0
41 2022-12-14  4.17  4.240  4.150    4.21         4.21  17683799.0
42 2022-12-13  4.13  4.130  4.060    4.06         4.06  17533878.0
43 2022-12-12  4.18  4.190  4.100    4.10         4.10  17689444.0
44 2022-12-09  4.14  4.240  4.140    4.19         4.19  16644968.0
45 2022-12-08  4.26  4.280  4.095    4.11         4.11  33483440.0
46 2022-12-07  4.33  4.390  4.320    4.33         4.33  24797008.0
47 2022-12-06  4.20  4.360  4.190    4.30         4.30  25169601.0
48 2022-12-05  4.31  4.370  4.290    4.34         4.34  24370952.0
49 2022-12-02  4.20  4.290  4.190    4.19         4.19  22760263.0
50 2022-12-01  4.16  4.320  4.150    4.29         4.29  34410284.0
51 2022-11-30  4.05  4.080  4.015    4.02         4.02  28713420.0
52 2022-11-29  3.96  4.070  3.905    4.07         4.07  22124678.0
53 2022-11-28  3.92  3.980  3.910    3.95         3.95  14526811.0
54 2022-11-25  4.05  4.050  3.995    4.02         4.02  10315454.0
55 2022-11-24  4.03  4.070  4.000    4.00         4.00  12637483.0
56 2022-11-23  4.00  4.020  3.970    4.01         4.01  12165904.0
57 2022-11-22  3.86  3.990  3.820    3.93         3.93  27870570.0
58 2022-11-21  3.89  3.910  3.815    3.85         3.85  23343428.0
59 2022-11-18  4.02  4.040  3.910    3.91         3.91  20865856.0
60 2022-11-17  4.16  4.170  3.990    4.00         4.00  27549550.0
61 2022-11-16  4.26  4.300  4.215    4.22         4.22  17879974.0
62 2022-11-15  4.20  4.280  4.200    4.28         4.28  20449389.0
63 2022-11-14  4.20  4.330  4.190    4.33         4.33  34307465.0
64 2022-11-11  4.04  4.090  3.995    4.09         4.09  23467753.0
65 2022-11-10  3.88  3.915  3.860    3.87         3.87  15185432.0
66 2022-11-09  4.00  4.000  3.920    3.92         3.92  22733923.0
67 2022-11-08  3.97  4.000  3.890    3.90         3.90  19604647.0
68 2022-11-07  3.96  3.970  3.860    3.95         3.95  17011184.0
69 2022-11-04  3.67  3.810  3.670    3.81         3.81  18482809.0
70 2022-11-03  3.66  3.710  3.660    3.68         3.68  17288046.0
71 2022-11-02  3.76  3.820  3.760    3.80         3.80  19728507.0
72 2022-11-01  3.63  3.725  3.630    3.72         3.72  14557393.0
73 2022-10-31  3.62  3.640  3.580    3.60         3.60  16747416.0
74 2022-10-28  3.69  3.720  3.600    3.60         3.60  16559143.0
75 2022-10-27  3.69  3.835  3.690    3.75         3.75  22489693.0
76 2022-10-26  3.62  3.700  3.605    3.64         3.64  21514966.0
77 2022-10-25  3.63  3.640  3.515    3.60         3.60  30131026.0
78 2022-10-24  3.77  3.840  3.640    3.65         3.65  33026474.0
79 2022-10-21  3.67  3.730  3.650    3.72         3.72  23257302.0
80 2022-10-20  3.72  3.730  3.600    3.67         3.67  44037696.0
81 2022-10-19  3.84  3.850  3.750    3.77         3.77  20553269.0
82 2022-10-18  3.81  3.860  3.775    3.85         3.85  18664493.0
83 2022-10-17  3.75  3.760  3.720    3.76         3.76  26805683.0
84 2022-10-14  3.84  3.860  3.790    3.84         3.84  14334721.0
85 2022-10-13  3.76  3.820  3.740    3.75         3.75  18057413.0
86 2022-10-12  3.65  3.730  3.650    3.70         3.70  24123802.0
87 2022-10-11  3.76  3.800  3.650    3.67         3.67  23698787.0
88 2022-10-10  3.83  3.840  3.780    3.78         3.78  13490172.0
89 2022-10-07  3.85  3.905  3.840    3.84         3.84  15682634.0
90 2022-10-06  3.85  3.930  3.850    3.90         3.90  32283674.0
91 2022-10-05  3.82  3.890  3.810    3.89         3.89  23021451.0
92 2022-10-04  3.69  3.780  3.655    3.75         3.75  38308643.0
93 2022-10-03  3.61  3.660  3.530    3.56         3.56  22216180.0
94 2022-09-30  3.68  3.700  3.630    3.63         3.63  32911358.0
95 2022-09-29  3.81  3.810  3.650    3.66         3.66  27149712.0
96 2022-09-28  3.78  3.800  3.640    3.66         3.66  19310665.0
97 2022-09-27  3.64  3.740  3.630    3.70         3.70  21754859.0
98 2022-09-26  3.70  3.730  3.580    3.59         3.59  24902143.0
99 2022-09-23  3.91  3.920  3.840    3.86         3.86  17612335.0

In [18]:
len(data)

100